### ISSUE TITLE
Unable to compile quadwild due to lack of gurobi

### ISSUE THREAD

**Issue by fire** [nicopietroni/quadwild#2]
On Rocky Linux (rhel8).

1. yum install boost-devel blas-devel ninja-build cmake
2. cd quadwild/libs/CoMISo
3. mkdir build
4. cd build
5. cmake .. -GNinja
1. ninja
1. sudo yum install -y qt5-devel
1. make

Unable to compile due to lack of gurobi.

**Comment by fire** [comment]
Investigating https://github.com/coin-or/Cbc as a replacement for gurobi.

See also https://github.com/ERGO-Code/HiGHS. https://github.com/ERGO-Code/HiGHS/blob/master/examples/call_highs_from_cpp.cpp

**Comment by fire** [comment]
https://gist.github.com/fire/891aa2be44834f24303f4d1c3905aebf Has a sample of using HiGHS as a MILP solver.

**Comment by lanxinger** [comment]
yep same issue here. Gurobi not found:

/home/xxx/quadwild/libs/quadretopology/quadretopology/includes/qr_ilp.h:32: error: gurobi_c++.h: No such file or directory
   32 | #include <gurobi_c++.h>
      |          ^~~~~~~~~~~~~~

**Comment by nicopietroni** [comment]
good point, we can try CbC soon.. at the moment I don't have any time to try the switch.
but we will certainly try in 3 weeks or so.
thanks for the idea

**Comment by fire** [comment]
According to a popular benchmark Highs is a better solver than CBC so if you’re limited by time, I recommend that one first. What solver do you need?

**Comment by nicopietroni** [comment]
integer variables with quadratic energy term and linear constraints

**Comment by jajhall** [comment]
Guessing that "quadratic energy term" is in the objective function, you are looking to solve mixed-integer quadratic programming (MIQP) problems. HiGHS _cannot_ solve MIQPs, although it is something we are looking to add, but not in the next 12 months.

Cbc itself cannot solve MIQP problems, but the following discussion may help you

coin-or/Sonnet#3

**Comment by fire** [comment]
Closing because https://github.com/nicopietroni/quadwild/issues/1, https://github.com/nicopietroni/quadwild/issues/14, https://github.com/nicopietroni/quadwild/issues/8 and this one are duplicates.
