### ISSUE TITLE
Relicense to be importabled into Godot Engine as a c++ module

### ISSUE THREAD

**Issue by fire** [nicopietroni/quadwild#4]
Hi!

It's ok, if you refuse, but I was wondering about your thoughts about relicensing to be Godot Engine compatible.

Godot Engine is MIT licensed.

MPL2 is good too.

## References

* https://opensource.org/licenses/MIT
* https://opensource.org/licenses/MPL-2.0

**Comment by nicopietroni** [comment]
currently we need some funds and maybe hire somebody to work to release the code for the Godot Engine.. hopefully in the near future will be possible

**Comment by fire** [comment]
Closing since there has been no change for almost a year.
