### ISSUE TITLE
Field Tracing Problem

### ISSUE THREAD

**Issue by zheSing** [nicopietroni/quadwild#5]
I found that in the function [**PreProcessMesh**](https://github.com/nicopietroni/quadwild/blob/d1c5d372d3371dac5a29bb92d468877a69b62aa8/components/field_tracing/tracing/vert_field_graph.h#L1573) , calling the function
`VertSplitter<MeshType>::SplitAlongEdgeSel(mesh);`
may cause parts of the mesh to be **non-manifold** (even if I didn't mark any sharp edge), and this is probably caused by the function 
`SplitAdjacentSingularities(mesh); `
(when I call both two functions, non-manifold vertices around singularities occur, otherwise not). 
Are those non-manifold parts desirable? Thanks for your answer.

**Comment by zheSing** [comment]
What I said "parts of the mesh to be non-manifold" is not correct, the mesh is still manifold, but `CountNonManifoldVertexFF(mesh)` will return a positive number, as some vertices' FF topology go wrong.

**Comment by zheSing** [comment]
**SORRY**, I found it was my problem. I changed wedge texture coordinates and caused a comparing error in  https://github.com/nicopietroni/xfield_tracer/blob/1d3097b997c1501b8d6398cc9ed31080a0defda6/tracing/vert_field_graph.h#L93
change it to 
`return (vA.cT().P() == vB.cT().P());`
will solve my problem.

**Comment by nicopietroni** [comment]
Thanks and sorry for the late reply
I am busy with teaching lately
N
